import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Toaster } from "react-hot-toast";
import { BsInfoLg } from "react-icons/bs";
import { FloatButton } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Join Metalogic Excitinng Career Opportunities in ...",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Toaster position='top-right' toastOptions={{ duration: 3000 }} />
        <div className="w-screen min-h-screen ">
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
